[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version = "0.2.1-b0"
update_changelog_on_bump = true
major_version_zero = true
version_files = [
    "phx.sh:PHX_VERSION",
    ".cz.toml:version"
]
